server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: kirby
                    uri: https://github.com/kirby239/Back_TheCodingBee_Micro.git
                    search-paths: config-data
    application:
        name: config-server
